version: '3'

services:
  app:
    build:
      context: .
    container_name: counter-image
    hostname: counter-image
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=BCP

  mongo:
    image: 'mongo:latest'
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"